### ISSUE TITLE
Clear the file-system at the end of each run

### ISSUE THREAD

**Issue by arokem** [arokem/python-matlab-bridge#1]
Make sure that nothing remains of a run in the file-system, regardless of what happens when it runs (for example if it crashes). This is important, because we run the risk of pulling in stuff from old runs into new runs.

**Comment by blink1073** [comment]
I'd say it is working fine as-is.  We are creating the diary and the figures in random temporary locations every time.  The only potential gotcha is that on Windows the temp location is not flushed, so we are adding to the existing garbage pile.

**Comment by arokem** [comment]
Agreed. Closing this for now.
