### ISSUE TITLE
passing matrix (dtype('float64')) containing NaNs to MATLAB

### ISSUE THREAD

**Issue by leizing** [arokem/python-matlab-bridge#100]
However, what I got in MATLAB is a cell array, which flatten the matrix. Assume the original matrix is 5 by 4, I end up with a 20 by1 cell array. Moreover, all NaNs are treated as strings 'NaN' in the cell. A bug or it is designed to be like this?

**Comment by blink1073** [comment]
This behaviour is fixed in the latest master:

```python
In [25]: S = np.ones((5,4), dtype=np.float64)

In [26]: S[0] = np.nan

In [27]: %%matlab -i S -o T
T = S;
   ....: 

In [28]: T
Out[28]: 
array([[ nan,  nan,  nan,  nan],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])
```
