### ISSUE TITLE
Make this repo standalone

### ISSUE THREAD

**Issue by dhermes** [arokem/python-matlab-bridge#104]
The fact that this repo is a fork makes it seem like it is not the main branch of development, but the parent branch certainly isn't either.

**Comment by arokem** [comment]
Thanks for the comment. I agree that this is confusing. On the one hand, I am reluctant to do that, because I would like to give @jaderberg the credit for sending is in this direction. On the other hand, we are doing that in the documentation (and we can do more). How would we go about doing this (technically speaking), without changing the github links?

**Comment by dhermes** [comment]
I'll go through the process by forking this to see how it works. Will report back.

As for giving credit, you can give a shout-out in the README.

**Comment by dhermes** [comment]
@arokem 

I was able to rename by visiting
https://github.com/dhermes/python-matlab-bridge/settings
and now it is named `python-matlab-bridge-foo`.

After which I could create a brand new repo named `python-matlab-bridge` and just push all the history there.

However, it won't port history so maybe the best solution is what is explained here:
http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository
From
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

> Commits made in a fork will not count toward your contributions. To make them count, 
> you must do one of the following:
> - Open a pull request to have your changes merged into the parent repository.
> - To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub support][1].

[1]: https://github.com/contact

**Comment by arokem** [comment]
Thanks. I'll take a look at all this, but probably will not do anything
before the middle of next week, so bear with me...

@jaderberg - any objections? We'll be sure to clearly give you credit for
all the work you did on this.

**Comment by dhermes** [comment]
I can file the issue with support and just point to this issue. If both @arokem and @jaderberg sign off, I doubt it'll be an issue. (Even @arokem comments above about how it was the inspiration but the core work has moved move.)

**Comment by isbadawi** [comment]
I think asking GitHub support is the "right" way of promoting this fork to
a root repo.

**Comment by dhermes** [comment]
@arokem GitHub says you need to file the ticket so they

> have a log of the request in our internal support system

**Comment by arokem** [comment]
Will do. Just waiting to hear from @jaderberg that he's OK with this.

**Comment by dhermes** [comment]
@arokem Cool. I reached out to @jaderberg by email and hope to hear back.

**Comment by jaderberg** [comment]
Hey guys I'm all fine with the move, it's a good idea!

On Thursday, 22 January 2015, Danny Hermes <notifications@github.com> wrote:

> @arokem <https://github.com/arokem> Cool. I reached out to @jaderberg
> <https://github.com/jaderberg> by email and hope to hear back.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arokem/python-matlab-bridge/issues/104#issuecomment-70963896>
> .
>


-- 
*Max Jaderberg <http://www.maxjaderberg.com/>*

m: +447513087348
t: @maxjaderberg
<http://twitter.com/maxjaderberg>l: Max Jaderberg LinkedIn
<http://www.linkedin.com/pub/max-jaderberg/32/39/9b1>

**Comment by arokem** [comment]
OK. Thanks everyone. I will file a ticket with github support.

**Comment by arokem** [comment]
All set!

**Comment by dhermes** [comment]
w00t!

**Comment by arokem** [comment]
This is what github support sends you when you ask to do this kind of thing: 

https://www.youtube.com/watch?v=gr_OpFxCx-A&t=1m43s

**Comment by dhermes** [comment]
Lulz
