### ISSUE TITLE
pymatbridge does not work on win32

### ISSUE THREAD

**Issue by willard-yuan** [arokem/python-matlab-bridge#122]
My python environment is as follows:

```sh
Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
```
and when I install **python-matlab-bridge**, it throws the error:

```sh
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    raise ValueError("pymatbridge does not work on win32")
ValueError: pymatbridge does not work on win32
```
My system is windows 7 64bits.

**Comment by arokem** [comment]
Thanks for reporting! Could you give this branch: #123 a try?

**Comment by russellsch** [comment]
Hello I am receiving the same error during install with the following environment:
> Python 2.7.8 |Anaconda 2.1.0 (64-bit)| (default, Jul  2 2014, 15:12:11) [MSC v.1500 64 bit (AMD64)] on win32

This is also under 64-bit Windows 7.

**Comment by arokem** [comment]
Hi - thanks for reporting. How did you install pymatbridge? I think that
the current master branch should have this fixed, so if you install from
source using `python setup.py install`, it should work. Let me know how
that goes!

**Comment by russellsch** [comment]
Yes that fixed my problems, everything seems to be working well now. Thanks much!
