### ISSUE TITLE
How do I load a mat file in python by python-matlab-bridge?

### ISSUE THREAD

**Issue by willard-yuan** [arokem/python-matlab-bridge#129]
Recently, I want to load  a mat file in python by python-matlab-bridge, not in a matlab function file since the mat file is very large. If I load the mat file in the matlab function, the process of loading the mat file will do every time when I call the function. This will cost much time. So how do I load a mat file in python by python-matlab-bridge?

In the matlab command windows, to load a mat file, we use `load('a.mat')`. I have tried to load it by `mlab.run_code()`, but it fails.

Please help me.

**Comment by arokem** [comment]
Is this what you are looking for?

http://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html

**Comment by blink1073** [comment]
Closing as answered, feel free to re-open if you disagree @willard-yuan.
