### ISSUE TITLE
cannot open libzmq.so.3 error 

### ISSUE THREAD

**Issue by emqiong** [arokem/python-matlab-bridge#131]
After installing the python-matlab-bridge. I run the following lines as instructed:
>>> from pymatbridge import Matlab
>>> mlab = Matlab()
>>> mlab.start()

This produce the following error
Invalid MEX-file
'/root/EmDev/anaconda/lib/python2.7/site-packages/pymatbridge/matlab/messenger.mexa64':
libzmq.so.3: cannot open shared object file: No such file or directory

Error in matlabserver (line 7)
messenger('init', socket_address)

I have libzmp installed, bthe following lines runs fine
>>> import zmq

How can I fix this error?

Thanks

**Comment by emqiong** [comment]
Just resolved the problem myself. 
apt-get install python-zmq

**Comment by arokem** [comment]
OK - thanks for reporting. Closing this for now.

**Comment by reinout91** [comment]
On my Arch system I found a way to solve the issue, (Which in my case occured for the Octave implementation) after installing  zeromq from the AUR repository and by the creation of two symlinks

In your install directory /usr/lib/octave/4.4.1
sudo ln -s liboctinterp.so liboctinterp.so.2

and in your /usr/lib:
sudo ln -s libzmq.so.5 libzmq.so.3

Note that you may have to change the versions for your install of Octave and zeromq 
Although I think it is a bit hacky. For now it works.
