### ISSUE TITLE
Double scalars not handled by Octave

### ISSUE THREAD

**Issue by blink1073** [arokem/python-matlab-bridge#138]
Simple test case yields `1` instead of `1.5`:

```
o = Octave()
o.start()
o.run_code('a=1.5')
o.get_variable('a')
```

This appears to be a limitation when calling `javaObject('org.json.JSONObject').toString()` in Octave.  I am using 3.8.1 in Ubuntu 14.04.  I traced `json_dump` and calling `toString()` on the `javaObject('java.lang.Double', value)` object works as expected, but not when it is rolled into the full JSON object.

**Comment by blink1073** [comment]
This causes 6 test failures when `USE_OCTAVE` is True.

**Comment by isbadawi** [comment]
Yes, I ran into this earlier when trying to make the Octave tests run on travis. I asked [a question on stackoverflow](http://stackoverflow.com/questions/28143406/calling-java-from-octave-with-double-arguments-loses-precision) but no replies. Not sure what's going on!

**Comment by blink1073** [comment]
As you pointed out, it works if we use the raw value.  Is there a case where doing so is a bad idea?

**Comment by blink1073** [comment]
The test suite passes with both Matlab and Octave if I use raw doubles [here](https://github.com/arokem/python-matlab-bridge/blob/master/pymatbridge/matlab/util/json_v0.2.2/json/json_dump.m#L146).

**Comment by isbadawi** [comment]
IIRC, I tried making that change before, and ran into errors where other parts of the code expected an object. Can you try with more complicated data structures, e.g. structs with double fields, etc?

**Comment by blink1073** [comment]
```python
In [2]: o.run_code('a.b=4332.22')
Out[2]: 
{'content': {'code': 'a.b=4332.22',
  'datadir': '/tmp/MatlabData/',
  'stdout': 'a =\n\n  scalar structure containing the fields:\n\n    b =  4332.2\n\n',
  'figures': []},
 'success': 'true'}

In [3]: o.get_variable('a')
Out[3]: {'b': 4332.22}
```

**Comment by blink1073** [comment]
```python
In [5]: m.run_code('a.b=4332.22')
Out[5]: 
{'content': {'code': 'a.b=4332.22',
  'datadir': '/tmp/MatlabData/',
  'stdout': 'a =\n\n  scalar structure containing the fields:\n\n    b =  4332.2\n\n',
  'figures': []},
 'success': 'true'}

In [6]: m.get_variable('a')
Out[6]: {'b': 4332.22}
```

**Comment by blink1073** [comment]
```python
In [9]: m.run_code('a.b=4332.22;a.c="apple"')
Out[9]: 
{'content': {'code': 'a.b=4332.22;a.c="apple"',
  'datadir': '/tmp/MatlabData/',
  'stdout': 'a =\n\n  scalar structure containing the fields:\n\n    b =  4332.2\n    c = apple\n\n',
  'figures': []},
 'success': 'true'}

In [10]: m.get_variable('a')
Out[10]: {'b': 4332.22, 'c': 'apple'}
```

```python
In [11]: m.run_code('a = {4332.22,"apple"}')
Out[11]: 
{'content': {'code': 'a = {4332.22,"apple"}',
  'datadir': '/tmp/MatlabData/',
  'stdout': 'a = \n{\n  [1,1] =  4332.2\n  [1,2] = apple\n}\n',
  'figures': []},
 'success': 'true'}

In [12]: m.get_variable('a')
Out[12]: [4332.22, 'apple']
```

**Comment by isbadawi** [comment]
Okay, here's the error I ran into, but it was while playing with `json_dump` at the octave prompt. Without the change:

```
+octave:1> javaaddpath('java/json.jar')
+octave:2> json_dump(5)
ans = 5.0
```

With the change (replacing the line you mention with `obj = value;`):

```
+octave:1> javaaddpath('java/json.jar')
+octave:2> json_dump(5)
error: scalar cannot be indexed with .
error: evaluating argument list element number 1
error: called from:
error:   /Users/isbadawi/code/py/python-matlab-bridge/pymatbridge/matlab/util/json_v0.2.2/json/json_dump.m at line 70, column 11
```

Line 70 tries to do an `obj.toString()`. Maybe we just never trigger the error case from our code?

**Comment by blink1073** [comment]
Yeah, I don't think we'd ever get into that case because we are always returning structures.
