### ISSUE TITLE
Documentation Overhaul

### ISSUE THREAD

**Issue by blink1073** [arokem/python-matlab-bridge#149]
I'd like to overhaul the documentation similar to [Oct2Py](http://blink1073.github.io/oct2py/).  This would declutter the Readme and provide a more professional image.  Any objections/suggestions?

**Comment by arokem** [comment]
That would be great. I see that you have sphinx on oct2py: seems like a
good direction.

We should give some thought to how we might integrate ipython notebooks
into sphinx documentation.

There may be a way to have live notebooks running somehow. Check out this
sorcery: http://sharky93.github.io/docs/gallery/auto_examples/

On Wed, Feb 18, 2015 at 11:16 AM, Steven Silvester <notifications@github.com

**Comment by blink1073** [comment]
Oooh, pretty, how did I not know about that?

**Comment by blink1073** [comment]
Closing as stale, I don't have the bandwidth.
