### ISSUE TITLE
"Splash" now shows up when starting matlab

### ISSUE THREAD

**Issue by arokem** [arokem/python-matlab-bridge#154]
Might have to do with the `nodisplay` flag removed here:

https://github.com/blink1073/python-matlab-bridge/commit/83262f218c6a32fd6d197f107a10d399775f0f3a

**Comment by blink1073** [comment]
Yes, this is so we can control visibility and not throw an error for imshow.

**Comment by arokem** [comment]
So you're saying this is a feature, not a bug?

**Comment by blink1073** [comment]
A necessary evil, I suppose.

**Comment by arokem** [comment]
Does it have to be the default behavior?

**Comment by blink1073** [comment]
Ah, there is a -nosplash option. 



—

**Comment by arokem** [comment]
Nice!
