### ISSUE TITLE
run_code doesn't show the complete error message

### ISSUE THREAD

**Issue by srvanrell** [arokem/python-matlab-bridge#160]
May be there is a way to get the complete error message but i don't know how.
Let me explain the problem with a minimal example.

If I define a function `foo.m` like the following...

    function output foo ( input )
      output = 3 + fancy(input);
    end

... where `fancy` function is not defined. 
When I try to run `foo` function using pymatbridge (`mlab.run_code('foo(3)')`) I only get this:

    {u'content': {u'code': u'foo(3)',
     u'stdout': u"Undefined function 'fancy' for input arguments of type 'double'."},
     u'success': u'false'}
 
While if I run the same function in matlab I get this extended message:

    >> foo(3)
    Undefined function 'fancy' for input arguments of type 'double'.
    
    Error in prueba (line 5)
    output = 3 + fancy(input);

How can I get the complete message using pymatbridge?
Thanks in advance

**Comment by arokem** [comment]
This seems to be due to Matlab's error handling: 

```matlab
>> try
foo(3)
catch ME
ME
end

ME = 

  MException with properties:

    identifier: 'MATLAB:UndefinedFunction'
       message: 'Undefined function 'fancy' for input arguments of type 'doub...'
         cause: {}
         stack: [1x1 struct]

>> ME.message

ans =

Undefined function 'fancy' for input arguments of type 'double'.

```

**Comment by arokem** [comment]
I stand corrected! It seems that the `stack` variable does keep a full record of everything. Let me see if we can parse the error a bit nicer for you.

**Comment by brunobeltran** [comment]
shouldn't this issue be closed?

**Comment by isbadawi** [comment]
I think so. When I made that PR I thought this issue was about the matlab magic, but it looks like it's just about `run_code`, which is fixed.
