### ISSUE TITLE
cannot open libzmq.so.3

### ISSUE THREAD

**Issue by raul678** [arokem/python-matlab-bridge#177]
I use python from anaconda through tcsh.

After mlab.start(), I met this error.

'''
Invalid MEX-file
'/chimerahomes/jingtao/anaconda/lib/python2.7/site-packages/pymatbridge/matlab/messenger.mexa64':
libzmq.so.3: cannot open shared object file: No such file or directory

Error in matlabserver (line 7)
messenger('init', socket_address);
'''

I found the location of libzmq.so.3 is /chimerahomes/jingtao/anaconda/lib. And I add this to DYLD_LIBRARY_PATH in .cshrc file. 
'''
setenv LD_LIBRARY_PATH /opt/stow/cuda/cuda-5.0.35/lib64
setenv DYLD_LIBRARY_PATH /chimerahomes/jingtao/anaconda/lib
'''

Also I installed pyzmq via 'conda install pyzmq'.

How can I fix it? 
Thanks :)

**Comment by arokem** [comment]
Hi - are you installing pymatbridge from the current `master` or from a released version?

**Comment by raul678** [comment]
Hi I use "pip install pymatbridge"..

**Comment by arokem** [comment]
I think that the recent changes on the `master` branch of the repo might help you. Would you mind trying to download the code from the repo and installing using `python setup.py install`?

**Comment by kjaquier** [comment]
I have the same issue on Ubuntu 14.04 with Python 3.4. My whole project is in a virtual environment, so I installed pyzmq in it, and then pymatbridge. Both using pip.

**Comment by arokem** [comment]
Hi - could you try installing from source instead? It should solve this
problem. We should put out another release soon...

**Comment by kjaquier** [comment]
Alright, so I followed the instructions on the README to do so. These are not exactly correct ; the following commands :

    python make.py
    ...
    python setup.py

Must be replaced with :

    python make.py matlab
    ...
    python setup.py install

And `python make.py matlab` gave an error (`Not a directory`). But the setup worked.
I also had to install numpy.

Anyway, at the end it worked, I could execute some Matlab code and get the result. Even in the virtual environement (just need to activate it before running `python setup.py install`).
I'm still waiting for a more convenient package though :wink:

**Comment by arokem** [comment]
Is this what you meant? https://github.com/arokem/python-matlab-bridge/pull/181

**Comment by kjaquier** [comment]
Yes, well, I guess its also `python setup.py install`for Octave.
Also, it's written in the introduction that Numpy is only necessary for the Matlab magic extension, which apparently is not case.

**Comment by arokem** [comment]
Thanks for the feedback - I updated the PR accordingly.

**Comment by arokem** [comment]
Closing this (?)
