### ISSUE TITLE
"Error writing to output stream" on alternating calls of `run_code()`

### ISSUE THREAD

**Issue by neuromusic** [arokem/python-matlab-bridge#180]
my initial discovery of this issue is outlined at arokem/python-matlab-bridge#171
I suspect that this is the same problem as Calysto/matlab_kernel#8

Basically, I'm running pymatbridge from an iPython notebook server. The first Matlab() instance (or the first matlab_kernel that is created) returns "Error writing to output stream" *on every other call*

So the following code...
``` python
from pymatbridge import Matlab
mlab = Matlab()
mlab.start()
print mlab.run_code('a = [1,2,3,4]')
print mlab.run_code('a = [1,2,3,4]')
print mlab.run_code('a = [1,2,3,4]')
print mlab.run_code('a = [1,2,3,4]')
```
returns
```
{u'content': {u'datadir': u'/tmp/MatlabData/', u'code': u'a = [1,2,3,4]', u'figures': [], u'stdout': u'\na =\n\n     1     2     3     4\n\n'}, u'success': u'true'}
{u'content': {u'code': u'a = [1,2,3,4]', u'stdout': u'Error writing to output stream.\n\n'}, u'success': u'false'}
{u'content': {u'datadir': u'/tmp/MatlabData/', u'code': u'a = [1,2,3,4]', u'figures': [], u'stdout': u'\na =\n\n     1     2     3     4\n\n'}, u'success': u'true'}
{u'content': {u'code': u'a = [1,2,3,4]', u'stdout': u'Error writing to output stream.\n\n'}, u'success': u'false'}
```
Bizarro.

Also, the figures it returns are not formatted the same as subsequent instances. The are smaller and more pixelated.

**Comment by arokem** [comment]
I am not seeing this here. I suspect that you are running an installation
of the last release? Would you mind updating to current master and giving
it another try?

We should put out a release soon (I'm thinking Monday, unless someone has
objections), so release installations should work as well, but we need
feedback to see that things really are working on master.

**Comment by neuromusic** [comment]
upgraded to master and now things have totally broken.

pymatbridge can't start matlab.

output after mlab.start()...

``` python
Starting MATLAB on ZMQ socket ipc:///tmp/pymatbridge
Send 'exit' command to kill the server
............................................................MATLAB session timed out after 60 seconds

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-ec1007d95844> in <module>()
      1 from pymatbridge import Matlab
      2 mlab = Matlab('/usr/local/MATLAB/R2015a/bin/matlab')
----> 3 mlab.start()

/usr/local/home/jkiggins/Code/python-matlab-bridge/pymatbridge/pymatbridge.py in start(self)
    216             return self
    217         else:
--> 218             raise ValueError("%s failed to start" % self._program_name())
    219 
    220     def _response(self, **kwargs):

ValueError: MATLAB failed to start
```

checking my ipython log...
```
[I 10:14:04.738 NotebookApp] Kernel started: 5d7d4e87-ef8e-47e0-9e8d-eb0bcfb13203
Invalid MEX-file
'/usr/local/home/jkiggins/Code/python-matlab-bridge/pymatbridge/matlab/messenger.mexa64':
/lib64/libc.so.6: version `GLIBC_2.17' not found (required by
/usr/local/home/jkiggins/Code/python-matlab-bridge/pymatbridge/matlab/messenger.mexa64)

Error in matlabserver (line 7)
messenger('init', socket_address);
```

FWIW, I installed from master with `pip install -e ./`

**Comment by neuromusic** [comment]
I'm on Scientific Linux 6 which is running glibc-2.12.

**Comment by arokem** [comment]
Ugh. Sorry about this. I don't think we were anticipating this...

What are your thoughts, @aebrahim?

**Comment by neuromusic** [comment]
Even Ubuntu 12.04LTS (which is being maintained until April 2017) is on glibc-2.15

- RHEL5: 2.5
- RHEL6: 2.12
- Ubuntu 12.04: 2.15

http://en.wikipedia.org/wiki/GNU_C_Library

**Comment by aebrahim** [comment]
Looking into this. If you build the mex yourself does it work?

**Comment by neuromusic** [comment]
@aebrahim nope. tried that :( at least I ran `make.py` and let it do its thing.

**Comment by aebrahim** [comment]
Did make.py succeed? If so, try running python setup.py install again. I
can't think of a good reason for that to fail.

**Comment by aebrahim** [comment]
I believe @jjangsangy is planning to hook make.py into setup.py but for the
time being they are still two separate steps.

**Comment by neuromusic** [comment]
OK. make.py then another pip install worked. no more glib errors.

aaand...

the "Error writing to output stream" error is gone now that I'm on master.

Thanks for your help!!

**Comment by mmagnuski** [comment]
It says `MATLAB session timed out after 60 seconds` - I think I have had this.
My matlab starts really slow and pymatbridge did not wait long enough.
In my case it works if you try to connect again to matlab with the same socket address, does it work for you?

**Comment by jjangsangy** [comment]
Sorry about the late updates. Currently moving around and the nomadic lifestyle makes it difficult to get any real work done.

### Changes

Likely I am thinking the merge for compilation and packaging will be very messy, since I'm starting to merge a lot of my branches on my end.

I will update a fork with the changes. I have a working copy that passes all unit tests, so people can start using that as __very beta__ solution if the traditional `make.py` doesn't do the trick.

### Setup
But ultimately the entire build and discovery process should be pretty seamless for unix systems running.

    python setup.py build_ext --inline

For windows based builds, it's a little more complicated but is mostly fixed by installing the required packages for the correct  (http://www.microsoft.com/en-us/download/details.aspx?id=44266)[MS VSC++ compiler tools.]

**Comment by jjangsangy** [comment]
Okay I lied

Run

```
python setup.py messenger
```

Now builds the binary into the main root folder.

This is highly highly beta, I have honestly shocked it actually works.

![screen shot 2015-04-22 at 9 38 27 am](https://cloud.githubusercontent.com/assets/3851682/7279827/8fecd4c0-e8d3-11e4-8fb5-8289fee7e73e.png)

**Comment by jjangsangy** [comment]
Also I forgot to mention, running

```
python setup.py test
```

Now runs the unit test suite.

![screen shot 2015-04-22 at 9 45 46 am](https://cloud.githubusercontent.com/assets/3851682/7279983/8fa94ab0-e8d4-11e4-9bf0-b9ed95a3b8fb.png)

**Comment by arokem** [comment]
Hey @jjangsangy - where is all this happening? Is this on one of your PRs? Or on a branch somewhere where I could take a look?

**Comment by jjangsangy** [comment]
Oh sorry, ya it's on this fork.

https://github.com/jjangsangy/python-matlab-bridge

**Comment by arokem** [comment]
It's on your `master` branch?

**Comment by jjangsangy** [comment]
Yup, I got a little stuck trying to rebasing these commits together, but ran into too many conflicts.

I think it's likely that we'll just have to work through a merge.

**Comment by arokem** [comment]
OK - I just tried a rebase - it's going to require some elbow grease. I can
give it a go later this week, or maybe early next week, if you don't get to
it before.

**Comment by jjangsangy** [comment]
Sure, I think my timeframe is similar. Now that we can compile using the setuptools machinery we can start deprecating components that are unnecessary and that will probably help make the transition a little easier.

I also don't mind explaining in details about how certain components work if that information is helpful as well!
