### ISSUE TITLE
Matlab found but throws error: Undefined function 'genpath' for input arguments of type 'char'.

### ISSUE THREAD

**Issue by rodonn** [arokem/python-matlab-bridge#190]
I tried getting my IPython set up to use python matlab bridge, but I got an error. In the command line output for the notebook server, I could see mat lab's text interface open up and then it gives error message "Undefined function 'genpath' for input arguments of type 'char'." After this pymatbridge eventually times out from hearing no response from Matlab.

![screen shot 2015-05-14 at 11 47 22 pm](https://cloud.githubusercontent.com/assets/2594443/7648112/99324bd8-fa93-11e4-8e09-56249f9410be.png)
![screen shot 2015-05-14 at 11 46 38 pm](https://cloud.githubusercontent.com/assets/2594443/7648110/991d4404-fa93-11e4-8f85-d05990d92c26.png)
![screen shot 2015-05-14 at 11 47 12 pm](https://cloud.githubusercontent.com/assets/2594443/7648111/9930f09e-fa93-11e4-8771-1d9c000dbc77.png)

**Comment by arokem** [comment]
That's odd.

What happens when you type `genpath` on the Matlab command line? Is your
Matlab `startup.m` file doing something to remove that file from your
Matlab path?

**Comment by rodonn** [comment]
Must have been something going weird with my server. I tried again today and it worked fine. Sorry for the false alarm.

**Comment by arokem** [comment]
No worries. Keep reporting strange things as they arise!
