### ISSUE TITLE
Building messenger.c upsets GCC 4.8.2

### ISSUE THREAD

**Issue by patricksnape** [arokem/python-matlab-bridge#203]
Using Matlab R2015a, I can't get messenger.c to build with ZMQ:

```
mex -O -L/home/pts08/miniconda/envs/_build/lib -I/home/pts08/miniconda/envs/_build/include -lzmq /home/pts08/miniconda/conda-bld/work/python-matlab-bridge-0.5.2/pymatbridge/messenger/src/messenger.c 
Building with 'gcc'.
Warning: You are using gcc version '4.8.2'. The version of gcc is not supported. The version currently supported with MEX is '4.7.x'. For a list of currently supported compilers see: http://www.mathworks.com/support/compilers/current_release.
Warning: You are using gcc version '4.8.2-19ubuntu1)'. The version of gcc is not supported. The version currently supported with MEX is '4.7.x'. For a list of currently supported compilers see: http://www.mathworks.com/support/compilers/current_release.
In file included from /home/pts08/miniconda/conda-bld/work/python-matlab-bridge-0.5.2/pymatbridge/messenger/src/messenger.c:5:0:
/home/pts08/miniconda/envs/_build/include/zmq.h:340:22: error: expected specifier-qualifier-list before ‘/’ token
     uint16_t event;  // id of the event as bitfield
```

However, if I change messenger.**c** to messenger.**cpp**, then it just complains about not properly casting the malloc on [L101](https://github.com/arokem/python-matlab-bridge/blob/master/pymatbridge/messenger/src/messenger.c#L101) to ``char*``.

Is there any particular reason that messenger.c is not a cpp file? Also, do you want a PR fixing that cast?

**Comment by isbadawi** [comment]
If it's just complaining about the comment, you can try specifying the C standard, something like this:

    mex CFLAGS='$CFLAGS -std=c99' -O -L/home/pts08/miniconda/envs/_build/lib -I/home/pts08/miniconda/envs/_build/include -lzmq /home/pts08/miniconda/conda-bld/work/python-matlab-bridge-0.5.2/pymatbridge/messenger/src/messenger.c

**Comment by patricksnape** [comment]
This also doesn't work on Windows - so how do you get it ti compile on Windows since Visual Studio 2010 and below don't support C99.

**Comment by isbadawi** [comment]
Looking at `zmq.h` on my system, it doesn't have those comments. I'm using 4.1.2. There seem to have be a few issues about things like this on the zmq repo (e.g. zeromq/libzmq#308, zeromq/libzmq#458), although I couldn't find the specific case you're running into.

Maybe someone else can chime in but it looks the solution would be to upgrade to a newer version of zmq?

**Comment by patricksnape** [comment]
Ah yes, fair comment, seems that the version shipped with conda is 4.0.5 which is obviously a lot older. I'll have to see if I can make a request for an update.

**Comment by isbadawi** [comment]
I never cast the result of malloc in C -- it's only required in C++ (one of the few ways in which C++ is not backwards compatible with C). Although I guess people go both ways on this. See e.g.: http://stackoverflow.com/questions/605845/do-i-cast-the-result-of-malloc

**Comment by patricksnape** [comment]
Fair enough, but as I said, if you want to properly ABI compatible on Python 2.7 on Windows, you need to be building against VS 2008. This doesn't include C99 support which makes things pretty awkward. Therefore, in general, it is easiest to just compile it as C++. Also, I don't really agree that guy, I like the Python way that explicit is always best and implicit casting of any form just promotes potential bugs from unintended casts.

Out of interest, how did you get this build on Windows?

**Comment by arokem** [comment]
I'll be honest and admit that this is all out of my range. There are some
notes about building the messenger on Windows here:

http://stackoverflow.com/questions/23716426/installing-pymatbridge-on-windows

But they might be slightly out-dated. Sorry to not be more helpful.

**Comment by isbadawi** [comment]
Going to close this. Presumably it was built on windows against a different version of zmq which didn't have that problem, so didn't require C99 support. Feel free to reopen if you still have issues.
