### ISSUE TITLE
Trivial issue on passing multiple arguments

### ISSUE THREAD

**Issue by nipunbatra** [arokem/python-matlab-bridge#229]
Hi
I'm trying to call a very simple function called `demoSum.M`

``` Matlab
function y = demoSum(a,b)
    y=a+b;
 end
```

Calling it as follows says that `Not enough input arguments`.

``` python
res = mlab.run_func('/Users/nipunbatra/Desktop/demo_sum.m', {'a':1,'b':2})
```

Calling as follows also doesn't work.

``` python
res = mlab.run_func('/Users/nipunbatra/Desktop/demo_sum.m',1,2, nargout=1)
```

Am I missing something really trivial. I have noted that in your examples you have made use of `args` and then extracting the variables from `args`. I thought that this was the only way possible till I stumbled upon this issue, where the function call was `mlab.run_func('multiply_them.m', dummy1, dummy2, dummy3, nargout=1)`

**Comment by Jvanschoubroeck** [comment]
Hello nipunbatra, are you conscious of the fact that the function name is `demoSum.m` and that the function you are calling using `mlab.run_func` is called `demo_sum.m`?

The error `Not enough input arguments` might just have put you on the wrong track.

**Comment by Jvanschoubroeck** [comment]
@arokem, I think this issue can be closed.
