### ISSUE TITLE
Jupyter notebook Matlab kernel busy all time

### ISSUE THREAD

**Issue by xavi87** [arokem/python-matlab-bridge#230]
Hello everbody,
I have to use the ipython notebook with matlab, so I have installed Anaconda3, Jupyter notebook, Pymatbridge , and matlab_kernel. when i launch a new file for python kernel --> it works, but when i do this for matlab kernel, it still busy all the time, so i can't run my matlab code.

I have tested this, in Windows 7 and Unix ubuntu, with anaconda3 and anaconda2.
Help me please !

**Comment by blink1073** [comment]
Hi @xavi87, are you able to run pymatbridge by itself?

**Comment by blink1073** [comment]
(from an IPython terminal)?

**Comment by xavi87** [comment]
Hi,
Thank you @blink1073 , i resolved my problem.
The problem was in the /.bashrc file to configure the Matlab path file.

Thank you very much

**Comment by blink1073** [comment]
Glad to hear it!  Closing the issue.
