### ISSUE TITLE
32 bit Matlab Messenger File not a valid Win32 application

### ISSUE THREAD

**Issue by jaxonc** [arokem/python-matlab-bridge#241]
I compiled using the Microsoft Software Development Kit (SDK) 7.1 compiler. When running I get the following error :

Invalid MEX-file 'C:\Python27\lib\site-packages\pymatbridge\matlab\src\messenger\mexw32\messenger.mexw32': C:\Python27\lib\site-packages\pymatbridge\matlab\src\messenger\mexw32\messenger.mexw32 is not a valid Win32
application.

Update 6-23-15: It appears this is because of an undeveloped messenger for windows 32bit systems.

**Comment by njman** [comment]
Here it's what I did for MATLAB r2014b 32 bit for Jupyter Notebook in Windows 10:

1\. Make sure VC++ and MATLAB bridged success for MEX build:

> \>\> mex -setup
> MEX configured to use 'Microsoft Visual C++ 2013 Professional (C)' for C language compilation.
> Warning: The MATLAB C and Fortran API has changed to support MATLAB
> 	 variables with more than 2^32-1 elements. In the near future
> 	 you will be required to update your code to utilize the
> 	 new API. You can find more information about this at:
>  .......... 

2\. Download and install [ZMQ](http://miru.hk/archive/ZeroMQ-4.0.4~miru1.0-x86.exe), actually I want to get header file, dll file, and lib file.

> libzmq-v90-mt-4_0_4.dll
> libzmq-v90-mt-4_0_4.lib
> zmq.h
> zmq_utils.h

3\. Copy the header/dll/lib file above to directory *pymatbridge\messenger\src\*.

4\. In MATLAB command window, run `mex messenger.c libzmq-v90-mt-4_0_4.lib`, then get the *messenger.mexw32*.

5\. copy *messenger.mexw32* and * libzmq-v90-mt-4_0_4.dll* to IPython pymatbridge directory (installed via Anaconda), i.e., *Miniconda2\envs\py2\Lib\site-packages\pymatbridge\matlab\*.

6\. Test in Jupyter notebook in my case.

```python
import pymatbridge as pymat
ip = get_ipython()
pymat.load_ipython_extension(ip)
```
Output:

```shell
Starting MATLAB on ZMQ socket tcp://127.0.0.1:65355
Send 'exit' command to kill the server
...........MATLAB started and connected!
```

For your reference.

**Comment by arokem** [comment]
Hey @njman : thanks for posting this here. Another good place to post this is on SO. Maybe as an answer to this question? http://stackoverflow.com/questions/31568649/install-pymatbridge-on-windows. Thanks again!

**Comment by jaxonc** [comment]
@njman Thanks!
