### ISSUE TITLE
macOS Monterey: Undefined function pops up when a python string is inserted as an argument.

### ISSUE THREAD

**Issue by gaveen99** [arokem/python-matlab-bridge#267]
Hi there,

when I try to send a python string to the MATLAB function and it throws an error as below.

 **{'result': '', 'success': False, 'content': {'stdout': "Undefined function 'lib' for input arguments of type 'struct'."}}**

Also, I tried converting to char and sending the argument. Unfortunately, the same error occurred.

Regards,
gaveen99

**Comment by arokem** [comment]
Looks like maybe this is a Matlab thing? https://www.mathworks.com/matlabcentral/answers/27160-input-arguments-of-type-struct#answer_570939.

**Comment by gaveen99** [comment]
> Looks like maybe this is a Matlab thing? https://www.mathworks.com/matlabcentral/answers/27160-input-arguments-of-type-struct#answer_570939.

Thank you for this solution. Got the output as desired.. pymatbridge FTW 😍

**Comment by gaveen99** [comment]
Hi There, 

I'm getting these errors when it tries to initiate the MATLAB instance. 

/Applications/MATLAB_R2022a.app/bin/matlab: line 398: awk: command not found
/Applications/MATLAB_R2022a.app/bin/matlab: line 414: expr: command not found
