### ISSUE TITLE
IMatlab — an IPython profile for exclusively Matlab code

### ISSUE THREAD

**Issue by mbauman** [arokem/python-matlab-bridge#34]
I have not spent any time looking into this yet, so I have no idea how feasible it may be with your current design (perhaps it should be a different project entirely).

But I love working within IPython.  And I'd love to be able to use full Matlab syntax (`@` anonymous functions, `%` comments, etc), with real Matlab-style syntax highlighting.  Could your project possibly be extended to add a profile for a Matlab backend to IPython?  I'm imagining something similar to [IJulia](https://github.com/JuliaLang/IJulia.jl).

This issue is just to test the waters for this approach.  Feel free to close if you think this is out of scope for this project.

**Comment by bilderbuchi** [comment]
FWIW, [Octave](https://github.com/calysto/octave_kernel) and [Matlab](https://github.com/calysto/matlab_kernel) Ipython seem to have been created in the meantime.

**Comment by arokem** [comment]
Yes. Since that issue was raised we've implemented the Matlab IPython
magic. The Matlab kernel you mentioned actually relies on pymatbridge to
communicate between IPython and Matlab.

On Tue, Jul 14, 2015 at 4:02 AM, Christoph Buchner <notifications@github.com

**Comment by mbauman** [comment]
Very cool.  Thanks for the update!
