### ISSUE TITLE
imshow() does not show picture

### ISSUE THREAD

**Issue by GKA103** [arokem/python-matlab-bridge#35]
Hi,

I was trying some image recognition but now imshow does not show the picture. No figure window opens, the program runs smoothly, no errors, imhist() works fine. It worked a couple of hours ago until Matlab R2013a crashed, I guess because calculations were a bit too complicated. It does "show" the number array in the command window if imshow(I) is called there...

Many thanks for your help!

**Comment by blink1073** [comment]
Closing as fixed.
