### ISSUE TITLE
object output argument  with string member

### ISSUE THREAD

**Issue by cekees** [arokem/python-matlab-bridge#44]
I was testing out the master branch and am seeing an error when matlab returns an object. The following notebook shows a simple version of the error. This was working in v0.1. 
http://nbviewer.ipython.org/gist/cekees/8669985

**Comment by blink1073** [comment]
Works in the latest master:

```python
In [4]: %%matlab -i s -o obj
obj.s = s
   ...: 

obj = 

    s: 'Hello world'
```
