### ISSUE TITLE
Use the output of ipython in a variable

### ISSUE THREAD

**Issue by garikoitz** [arokem/python-matlab-bridge#47]
Hi, is this possible?
I need to run some code in Matlab and then read the output which is only one number. I don't want to bring and brought back all the structures from Matlab.
When I use the iPython option I can see the correct answer (ans = ) in the iPython console, but I don't know how to use it in a variable. 

thanks for the project!
Gari

**Comment by blink1073** [comment]
Closing as answered.  Feel free to reopen @garikoitz if you disagree.
