### ISSUE TITLE
Repeated make code

### ISSUE THREAD

**Issue by ahmadia** [arokem/python-matlab-bridge#66]
In the `messenger` directory, the file `make.py` appears to be copied (with very minor modifications) separately into the Linux and OS X build directories.  It's not copied into the Windows directory, making for an inconsistent build experience.

The intention and usage of the `make.py` bootstrap script should be clarified.

**Comment by blink1073** [comment]
I'm calling this one fixed by #144.  Feel free to submit any cygwin specific changes @cekees.

**Comment by cekees** [comment]
Thanks. I haven't gotten around to updating pymatbridge in a while.  I
appreciate all the effort you guys are pointing into it and will try to get
our stack updated to a recent master at some point in the next month or so.
