### ISSUE TITLE
better JSON munging or workaround

### ISSUE THREAD

**Issue by shabbychef** [arokem/python-matlab-bridge#7]
The following will choke pymatbridge:
```
%%matlab
fprintf('got quotes? -->  "    ');
```
The JSON parser gets confused, of course. We can work on escaping and unescaping the I/O to and from Matlab, but it might make more sense to use temporary files (blech), or another mechanism, to move text around.

**Comment by blink1073** [comment]
Works on current master, closing as fixed.

```python
In [6]: %%matlab
   ...: fprintf('got quotes? -->  "    ');
   ...: 
got quotes? -->  "    
```
