### ISSUE TITLE
undefined function 'messenger'

### ISSUE THREAD

**Issue by fehiepsi** [arokem/python-matlab-bridge#71]
I am trying to run matlab code in ipython notebook. But I cannot manage to start `mlab.start()` following the guide after installation. My system information: ubuntu1 14.04, 32bit, matlab r2009b 32bit, anaconda 2.0.0 (with zeromq  4.0.4, pyzmq 14.3.0, pymatbridge 0.3). I also add 
`export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/home/fehiepsi/anaconda/lib/libzmq.so.3` to my `.profile` file.

It seems that the `messenger` function in `matlabserver.m` is not defined. Here is the error

```
< M A T L A B (R) >
                  Copyright 1984-2009 The MathWorks, Inc.
                 Version 7.9.0.529 (R2009b) 32-bit (glnx86)
                              August 12, 2009


  To get started, type one of these: helpwin, helpdesk, or demo.
  For product information, visit www.mathworks.com.

??? Undefined function or method 'messenger' for input arguments of type
'char'.

Error in ==> matlabserver at 7
messenger('init', socket_address);
```

**Comment by fightingalways** [comment]
@fehiepsi ,hello. I've encounted the same problem as you.However,  I cannot see @arokem's second reply. So, would you share your experience with me? Thanks ahead! I need your help very much......

**Comment by fehiepsi** [comment]
@fightingalways : if you are in the same problem as me, then the missing of 'mexa' file is the cause. To build it, you can follow the readme page https://github.com/arokem/python-matlab-bridge.

After you have generated the mex file (in my case, the name of that file is 'messenger.mexglx'), you copy it into the following folder: /python/site-packages/pymatbridge/matlab, where '/python' is your installed python folder.

**Comment by arokem** [comment]
Sorry for the delay in responding, and sorry to hear that you have been
having trouble getting this going. Hopefully the recent information from
@fehiepsi has been helpful. Otherwise - there will be more documentation
coming soon...
