### ISSUE TITLE
Performance using ZMQ

### ISSUE THREAD

**Issue by mfitzp** [arokem/python-matlab-bridge#72]
I've recently upgraded to the dev-0.4 version (from this repo) and am experiencing poorer performance on variable I/O compared to previous versions.

For example running the following in a Python cell creates a variable called e at 2.5MB:

    e = np.random.rand(32768,10)
    mb = e.nbytes / 1024**2.
    mb

Passing this into a Matlab cell and processing it as follows takes ~ 1m40s:

    %%matlab -i e -o f
    f=mean(e);

This is a lot slower than the previous implementation (I can't benchmark until I find where I installed it from!)

Is it possible to select the protocol/communication method when initialising the extension? Thanks

**Comment by blink1073** [comment]
I'd say this is fixed on the current master thanks to base64 encoding of arrays:

```python
In [15]: e = np.random.rand(32768, 10)

In [16]: %time m.mean(e);
CPU times: user 36.9 ms, sys: 10.4 ms, total: 47.4 ms
Wall time: 607 ms
Out[16]: 
{'content': {'datadir': '/tmp/MatlabData/', 'figures': [], 'stdout': ''},
 'result': array([[ 0.49988451,  0.50171806,  0.49738513,  0.49900619,  0.49779332,
          0.50118379,  0.50171328,  0.50040391,  0.50208133,  0.50055755]]),
 'success': True}
```
