### ISSUE TITLE
Memory used by MATLAB process keeps increasing

### ISSUE THREAD

**Issue by dawenl** [arokem/python-matlab-bridge#84]
First of all, thanks a lot for creating such an awesome extension! 

I've been using matlab magic recently on a project, which repeatedly calls the following function with random parameters:

```python
# mlab is initiated:
#     import pymatbridge as pymat
#     mlab = pymat.Matlab()

def matlab_bilinear(Bs, As, fs, fp):
    res = mlab.run_code('[Bz, Az] = bilinear(%s, %s, %s, %s);' % (Bs, As, fs, fp))
    Bz = mlab.get_variable('Bz')
    Az = mlab.get_variable('Az')
    return Bz, Az
```

After calling ```matlab_bilinear``` over 4 million times, the MATLAB process is using a substantial amount of memory (8% out of a 48GB-memory server) and apparently is still increasing. I don't think it is related specifically to the code I wrote, so I am wondering if there is any part which could cause memory leak very slowly or it's simply because the parameters are internally stored in memory by Matlab and keep accumulating. Any comments or suggestions are welcome. Thanks!

Best,
Dawen

**Comment by blink1073** [comment]
It appears this is now fixed.  I ran the following code (which ran for about 10 minutes), and there was less memory usage at the end than at startup:

```python
from pymatbridge import Matlab
m = Matlab()
m.start()

for i in range(20000):
    m.run_code("""
    Fs = 0.5;                             
    [z,p,k] = ellipap(6,5,90);            
    [num,den] = zp2tf(z,p,k);             
    [numd,dend] = bilinear(num,den,Fs);   
    """)
    numd = m.get_variable('numd')
    dend = m.get_variable('dend')
```

**Comment by blink1073** [comment]
Feel free to re-open @dawenl  if you disagree.
