### ISSUE TITLE
Support for 0mq 4.x

### ISSUE THREAD

**Issue by dukebody** [arokem/python-matlab-bridge#90]
I just installed pymatbridge and, when I try to start the server, it complains about not finding the file libzmq.so.3.  I have 0mq 4.0.5 installed so I have the file libzmq.so.4. 

I symlinked that one to libzmq.so.3 but I'm afraid this won't work realiably. Could you add 0mq 4.x support to pymatbridge?

**Comment by jakirkham** [comment]
I could be wrong, but I ran into a similar problem. The solution for me was to rebuild messenger ( https://github.com/arokem/python-matlab-bridge/tree/master/messenger ).

To do this you will need to edit the `local.cfg` file for your OS and add proper paths. Run `make.py` and it will generate a MATLAB binary and place it in your OS directory. Once this is complete, rerun `setup.py`.

**Comment by nils-werner** [comment]
Homebrew updated zeromq recently so messenger needs to be rebuilt: #130

**Comment by blink1073** [comment]
@dukebody, what OS are you using?  We now include zmq4 support by default in Windows and OSX, and you can get in in Linux by manually copying https://github.com/arokem/python-matlab-bridge/blob/master/messenger/mexa64/messenger.mexa64.zmq4 to `pymatbridge/matlab` as messenger as `messenger.mexa64`.

**Comment by dukebody** [comment]
@blink1073 I'm using Ubuntu Linux. Thanks for the instructions! I guess we can mark this issue as solved.

**Comment by blink1073** [comment]
Excellent @dukebody, we'll be updating our docs soon to reflect the new installation methods.
