### ISSUE TITLE
Matlab magic  "The pymatbridge module is not an IPython extension"

### ISSUE THREAD

**Issue by xhwang** [arokem/python-matlab-bridge#96]
Hi, all

My platform is 
* Windows 7 64bit
* Python 2.7.8 64bit
* IPython 2.3.1
* Matlab 2011a 64bit
* Visual Studio 2010

I download the master source code, comment the win32 test out and, after installing, build the messenger *"messenger.mexw64"* myself using mex.

I run the following code:

    from pymatbridge import Matlab
    mlab = Matlab()
    mlab.start()
    results = mlab.run_code('a=1;')
    print(results)
    mlab.stop()

It works. Here is the output:

    Starting MATLAB on ZMQ socket tcp://127.0.0.1:55555
    Send 'exit' command to kill the server
    ...MATLAB started and connected!
    {u'content': {u'datadir': u'C:\\Users\\Admin\\AppData\\Local\\Temp\\MatlabData\\', u'code': u'a=1;', u'figures': [], u'stdout': u''}, u'success': u'true'}
    MATLAB closed

But when I use it in the IPython notebook, it shows

    In [2]: %load_ext pymatbridge
    The pymatbridge module is not an IPython extension.

Does anyone have a clue? 
Best

**Comment by fehiepsi** [comment]
@xhwang I think that I have figured this out. We should install `numpy` (and maybe `scipy` also) first. The `matlab_magic` and `publish` modules require these packages.

**Comment by arokem** [comment]
Yes - agreed. In principle, the thing works with only pyzmq, but the ipython magic function does depend on scipy, numpy, and obviously ipython. Maybe should make it clearer in the README. Would that help, in your opinion?

**Comment by isbadawi** [comment]
An option might be to split this off into two separate packages on pip, one with the core MATLAB communication, and another with just the ipython stuff (and with a dependency on the first). It might even make sense to split this repo into different ones along the same lines -- `matlab_magic.py` is sort of its own module already, with nothing depending on it.

**Comment by arokem** [comment]
That seems like a bit of overkill (and a maintenance PITN). Who would be
using this without numpy anyway?

**Comment by isbadawi** [comment]
My thesis project was a sort of MATLAB IDE (https://github.com/Sable/mclab-ide), and I used this library to implement the command prompt. It is a bit unusual though :s

**Comment by arokem** [comment]
That's fantastic!

But maybe also an exotic use-case?

**Comment by febedtu** [comment]
Sorry for reviving this but I am running into the same issue, without being able to use the "workaround", i.e. not using `%load_ext pymatbridge`

Any idea what might the source of this issue?

**Comment by lanluo9** [comment]
> Sorry for reviving this but I am running into the same issue, without being able to use the "workaround", i.e. not using `%load_ext pymatbridge`

Same here. Did you figure out how to solve this by any chance?
