### ISSUE TITLE
Is it possible to leverage only one Matlab instance?

### ISSUE THREAD

**Issue by Sycomore74** [arokem/python-matlab-bridge#98]
I have noticed that the two different ways to access matlab create two different instances:

from pymatbridge import Matlab
 mlab = Matlab() mlab.start()
mlab.run_code("1+1");

and

%load_ext pymatbridge

create two different Matlab instances.

Is it possible to create only one Matlab instance, but that can be accessed with both methods?

**Comment by blink1073** [comment]
I'm calling this one solved, feel free to reopen if you disagree @Sycomore74.
